version: "3.8"

services:
  rstudio:
    image: nlpsandbox/nlpsandbox-analysis:edge
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlpsandbox-analysis
    command: rstudio
    env_file:
      - .env
    volumes:
      - .:/home/rstudio/nlpsandbox:rw
    networks:
      - data-node
    ports:
      - "${HOST_PORT}:8787"

networks:
  data-node:
    external: true
    name: data-node_default
